AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for simple ecs service scheduler app

Globals:
  Function:
    Timeout: 3

Resources:
  ECSServiceSchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: simple_ecs_service_scheduler/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        7amweekdays:
          Type: CloudWatchEvent
          Properties:
            Pattern:
            Input: {"rulename": "7amweekdays", "behavior": "scaleup"}
        7pmweekdays:
          Type: CloudWatchEvent
          Properties:
            Pattern:
            Input: {"rulename": "7pmweekdays", "behavior": "scaledown"}

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
