AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for simple ecs service scheduler app

Globals:
  Function:
    Timeout: 3

Resources:
  ECSServiceSchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: simple_ecs_service_scheduler/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
       - AWSLambdaExecute # Managed Policy
       - AmazonECS_FullAccess # Managed Policy
      Events:
        7amweekdays:
          Type: Schedule
          Properties:
            Schedule: "cron(0 5 * * MON-FRI *)"  # time in utc, so -2 hours to ams https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
            Input: '{"rulename": "7amweekdays", "behavior": "scaleup"}'
        7pmweekdays:
          Type: Schedule
          Properties:
            Schedule: "cron(0 17 * * MON-FRI *)" # time in utc, so -2 hours to ams
            Input: '{"rulename": "7pmweekdays", "behavior": "scaledown"}'

Outputs:
  ECSServiceSchedulerFunction:
    Description: "ECSServiceScheduler Lambda Function ARN"
    Value: !GetAtt ECSServiceSchedulerFunction.Arn
  ECSServiceSchedulerFunctionIamRole:
    Description: "Implicit IAM Role created for ECSServiceScheduler function"
    Value: !GetAtt ECSServiceSchedulerFunction.Arn
